[2023-09-06 17:34:48,801] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:34:51,642] WARNING add_tutor() L58   Erro ao adicionar tutor 'Jos√©', Tutor de mesmo nome j√° salvo na base :/ - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py L58  
[2023-09-06 17:34:51,644] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:34:51] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:02,562] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:02,706] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:04,707] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:35:04,711] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:35:04] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:11,632] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:12,024] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:13,362] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:35:13,365] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:35:13] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:40,149] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:35:40,404] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:04,082] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:08,105] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:36:08,110] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:36:08] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:09,232] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:36:09,233] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:36:09] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:42,693] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:43,197] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:45,914] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:36:45] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:56,423] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:56,585] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:36:58,373] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:36:58] "[31m[1mPOST /tutor HTTP/1.1[0m" 409 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:37:21,024] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:37:21,211] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:37:46,972] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:38:11,858] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:38:31,209] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:38:36,700] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:38:53,421] INFO _log() L224   * Restarting with stat - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
