[2023-09-06 17:33:58,241] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:34:04,740] INFO _new_conn() L757  Starting new HTTPS connection (1): emailvalidation.abstractapi.com - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py L757 
[2023-09-06 17:34:05,578] ERROR log_exception() L1449 Exception on /tutor [POST] - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py L1449
Traceback (most recent call last):
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1520, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1539, in finalize_request
    response = self.make_response(rv)
  File "/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a set.
[2023-09-06 17:34:05,583] INFO _log() L224  127.0.0.1 - - [06/Sep/2023 17:34:05] "[35m[1mPOST /tutor HTTP/1.1[0m" 500 - - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
[2023-09-06 17:34:48,661] INFO _log() L224   * Detected change in '/Users/tairik/PycharmProjects/mvp-tairik/rest_api_tutores/app.py', reloading - call_trace=/Users/tairik/PycharmProjects/mvp-tairik/venv/lib/python3.9/site-packages/werkzeug/_internal.py L224 
